### ISSUE TITLE
Build fails with recent strawberry perl versions

### ISSUE THREAD

**Issue by jochenpee** [rschupp/PAR-Packer#28]
I cannot find a strawberry perl version that works. Last version I had working was Perl 5.8.9.4 with PP 1.010.
I am lost, please help.

Test Summary Report 
------------------- 
t/20-pp.t              (Wstat: 512 Tests: 34 Failed: 2) 
  Failed tests:  33-34 
  Non-zero exit status: 2 
Files=17, Tests=243, 2684 wallclock secs ( 0.39 usr +  0.23 sys =  0.62 CPU) 
Result: FAIL 
Failed 1/17 test programs. 2/243 subtests failed. 
gmake: *** [Makefile:1033: test_dynamic] Error 255 
  RSCHUPP/PAR-Packer-1.050.tar.gz 
  C:\Users\l0106086\Documents\strawberry-perl-5.32.0.1-64bit-portable\c\bin\gmake.exe test -- NOT OK 
//hint// to see the cpan-testers results for installing this module, try: 
  reports RSCHUPP/PAR-Packer-1.050.tar.gz 
Stopping: 'install' failed for 'R/RS/RSCHUPP/PAR-Packer-1.050.tar.gz'.

**Comment by rschupp** [comment]
>  C:\Users\l0106086\Documents\strawberry-perl-5.32.0.1-64bit-**portable**\c\bin\gmake.exe test -- NOT OK

PAR-Packer doesn't work with the "Portable edition" of Strawberry Perl, use another edition.

**Comment by shawnlaffan** [comment]
I've been using the Strawberry Perl portable edition for several versions without issue, since at least perl 5.22.  I just tested PAR::Packer 1.50 using perl 5.28 and it passes all tests.  

@jochenpee - make sure you run the portable shell at the top level of the strawberry perl directory so the paths are set correctly.  Look for ```portableshell.bat```.  

You might also be hitting issues with antivirus software, so check any logs for PAR::Packer related files in quarantine (although I would expect more tests to fail if that were the case).

**Comment by rschupp** [comment]
@shawnlaffan I stand corrected :grinning: 

@jochenpee Failures in tests 33-34 in t/20-pp.t are relatively harmless (they test "pp -a ..." and "pp -A ...")

**Comment by jochenpee** [comment]
@rschupp @shawnlaffan  Thanks for the quick response and all the hints! I use the ZIP version now and it seems to work! I assumed I could not write to C:\ in Win10, but I was wrong. 
And now the ZIP version only needs a dir without spaces, maybe this is also valid for the portable version.
