### ISSUE TITLE
Producing binaries for multiple architectures

### ISSUE THREAD

**Issue by life00** [rschupp/PAR-Packer#91]
Hey so I am trying to figure out if its possible to produce lets say an `aarch64` architecture binary from an `x86_64` linux machine. I read the manual, but it does not seem to have an option to set the target architecture. I am hoping that maybe there could be some undocumented environment variable that I could set in order to specify the target architecture (instead of the current system architecture).

If there is no such environment variable then I suggest this to be a feature request. Thanks

**Comment by rschupp** [comment]
> I am trying to figure out if its possible to produce lets say an aarch64 architecture binary from an x86_64 linux machine

@life00 TL;DR That's not possible and it's highly unlikely that such a feature will be implemented.

The `--multiarch` option of `pp` works only when packing a `.par` file. All it does is packing Perl modules into a sub directory named after the host architecture in the resulting zip file (instead of directly under the root). There's no mention of a "foreign" architecture here. Actually, I don't know what this was intended for. Maybe so you could pack the same script (into a `.par`) on different machines with different architectures and later somehow combine these `.par` files into a "fat" `.par`? But you'll need these different machines (each with an installation of perl and all modules required by your script) anyway.
